#tag::security[]
micronaut:
  security:
    authentication: bearer  # <1>
    token:
      jwt:
        signatures:
          secret:
            generator: # <2>
              secret: pleaseChangeThisSecretForANewOne # <3>
#end::security[]